// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itmegnklwvtitwknyvkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0bWVnbmtsd3Z0aXR3a255dmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzY3NDEsImV4cCI6MjA1OTc1Mjc0MX0.Os4TZU23xZAYRipTQgP6J_EV2vBYrvDqi5g4p7rrsYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);